{% set name = "orange-canvas-core" %}
{% set version = "0.1.33" %}
{% set sha256 = "c3792b8a3efe0ad265d57a09cf7451000a7668aa8c09083f3c18797ab7ff3e1b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - anyqt >=0.2.0
    - docutils
    - commonmark >=0.8.1
    - requests
    - requests-cache
    - pip >=18.0
    - dictdiffer
    - qasync
    - pyqt
    - importlib_metadata
    - packaging
    - numpy

test:
  imports:
    - orangecanvas.main
    - orangecanvas.application.canvasmain

about:
  home: https://github.com/biolab/orange-canvas-core
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Core component of Orange Canvas

  description: |
    Orange Canvas Core is is a framework for building graphical user
    interfaces for editing workflows. It is a component used to build
    the Orange Canvas (http://orange.biolab.si) data-mining application
    (for which it was developed in the first place).

  doc_url: https://orange-canvas-core.readthedocs.io/
  dev_url: https://github.com/biolab/orange-canvas-core

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
